# Generated by Django 5.0.1 on 2024-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('cenaNakup', models.IntegerField()),
                ('cenaProdej', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('primeni', models.CharField(max_length=50)),
                ('datumNarozeni', models.DateField()),
                ('nakup', models.ManyToManyField(blank=True, related_name='Zakaznik', to='tabulka.item')),
            ],
        ),
    ]
